---
# Source: splunk-otel-collector/charts/obi/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: default-obi
  namespace: default
  labels:
    helm.sh/chart: obi-0.11.0
    app.kubernetes.io/name: obi
    app.kubernetes.io/instance: default
    app.kubernetes.io/version: "v0.10.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: obi
    app.kubernetes.io/component: workload
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: obi
      app.kubernetes.io/instance: default
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: e1ccaba722b72f92f46483abb82be827625cc12f3fb435b93cd3f2a0f5ea28b9
        
      labels:
        helm.sh/chart: obi-0.11.0
        app.kubernetes.io/name: obi
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "v0.10.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: obi
        app.kubernetes.io/component: workload
    spec:
      serviceAccountName: default-obi
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
      containers:
        - name: ebpf-instrument
          image: ghcr.io/open-telemetry/opentelemetry-ebpf-instrumentation/ebpf-instrument:v0.10.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
          - name: metrics
            containerPort: 9090
            protocol: TCP
          env:
            - name: OTEL_EBPF_CONFIG_PATH
              value: "/etc/ebpf-instrument/config/ebpf-instrument-config.yml"
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: "OTEL_EBPF_KUBE_CLUSTER_NAME"
              valueFrom:
                configMapKeyRef:
                  key: OTEL_EBPF_KUBE_CLUSTER_NAME
                  name: splunk-otel-collector-obi-env
          volumeMounts:
            - mountPath: /etc/ebpf-instrument/config
              name: ebpf-instrument-config
            - mountPath: /sys/fs/cgroup
              name: cgroup
              readOnly: true
            - mountPath: /sys/kernel/tracing
              name: tracefs
            - mountPath: /sys/kernel/security
              name: kernel-security
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
        - name: ebpf-instrument-config
          configMap:
            name: default-obi
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: tracefs
          hostPath:
            path: /sys/kernel/tracing
        - hostPath:
            path: /sys/kernel/security
            type: Directory
          name: kernel-security
