name: Configure GKE Kubernetes Context
description: Configure kubeconfig for GKE cloud functional tests.

inputs:
  gke-project-id:
    description: GKE project ID.
    required: true
  gke-credentials-json:
    description: GKE service account credentials JSON.
    required: true
  gke-cluster-name:
    description: GKE cluster name.
    required: true
  gke-location:
    description: GKE cluster location.
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        project_id: ${{ inputs.gke-project-id }}
        credentials_json: ${{ inputs.gke-credentials-json }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
      with:
        project_id: ${{ inputs.gke-project-id }}

    - name: Install GKE kubeconfig
      uses: google-github-actions/get-gke-credentials@3da1e46a907576cefaa90c484278bb5b259dd395 # v3.0.0
      with:
        cluster_name: ${{ inputs.gke-cluster-name }}
        location: ${{ inputs.gke-location }}
        project_id: ${{ inputs.gke-project-id }}
