clusterName: CHANGEME
splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME

targetAllocator:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
