clusterName: CHANGEME
splunkPlatform:
  token: CHANGEME
  endpoint: http://localhost:8088/services/collector
  metricsEnabled: true
  metricsIndex: CHANGEME

splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME
  metricsEnabled: false

featureGates:
  useControlPlaneMetricsHistogramData: true
  enableSplunkO11yOTLPHistograms: true
