clusterName: CHANGEME
splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME
  metricsEnabled: true
  tracesEnabled: true

splunkPlatform:
  endpoint: CHANGEME
  token: CHANGEME
  logsEnabled: true

distribution: ""
cloudProvider: ""

isWindows: true
logsEngine: otel
readinessProbe:
  initialDelaySeconds: 60
livenessProbe:
  initialDelaySeconds: 60
