clusterName: CHANGEME
splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME

gateway:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 2
      memory: 4Gi
  service:
    annotations:
      gateway: "test-value"
  mode: statefulset
  statefulsetSpec:
    volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    podManagementPolicy: Parallel

agent:
  enabled: false
clusterReceiver:
  enabled: false
