# EKS Add-on requires minimal configuration for the Helm chart to be rendered correctly.
# splunkObservability.realm and splunkObservability.accessToken must be set by the user or
# set to empty strings if splunkPlatform is used instead.
splunkObservability:
  realm: CHANGEME
  accessToken: CHANGEME

# Default values for running in AWS EKS
cloudProvider: aws
distribution: eks

# Only ECR repositories can be used for EKS Add-on images.
image:
  otelcol:
    repository: ${ECR_OTELCOL_REPO}
  initPatchLogDirs:
    repository: public.ecr.aws/docker/library/almalinux
    tag: "9"
  validateSecret:
    repository: public.ecr.aws/docker/library/almalinux
    tag: "9"

# A required shared library for journalctl is under /usr/lib64 on Amazon Linux 2023. The default mnts configuration has
# to be overridden to include this path for the journald receiver to work properly in EKS Add-on.
logsCollection:
  journald:
    directory: /var/log/journal
    mnts:
      - name: host-lib64
        path: /lib64
      - name: host-lib
        path: /lib
      - name: host-usr-lib
        path: /usr/lib
      - name: host-usr-lib64
        path: /usr/lib64
