---
# Source: splunk-otel-collector/charts/targetallocator/templates/clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: default-targetallocator-ta-clusterRole
  labels:
    helm.sh/chart: targetallocator-0.127.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: opentelemetry-target-allocator
    app.kubernetes.io/version: "0.126.0"
    app.kubernetes.io/name: targetallocator
    app.kubernetes.io/instance: default
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - alertmanagers
      - prometheuses
      - prometheuses/finalizers
      - alertmanagers/finalizers
      - servicemonitors
      - podmonitors
      - prometheusrules
      - probes
      - scrapeconfigs
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - '*'
  - apiGroups: [""]
    resources:
      - namespaces
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
