name: instrumentation-cr-test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  instrumentation-cr-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'Ignore Tests') }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: ./.github/actions/functional-test
        with:
          k8s-version: v1.34.3
          suite: instrumentation_cr
          go-version-file: functional_tests/go.mod
          build-test-images: 'false'
          artifact-suffix: instrumentation-cr
