name: instrumentation-cr-test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  instrumentation-cr-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'Ignore Tests') }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v5
        with:
          go-version-file: functional_tests/go.mod
          cache-dependency-path: functional_tests/go.sum
      - name: Create kind cluster
        uses: helm/kind-action@v1.14.0
        with:
          node_image: kindest/node:v1.34.3
          kubectl_version: v1.34.3
          cluster_name: kind
          config: ./.github/workflows/configs/kind-config.yaml
      - name: Fix kubelet TLS server certificates
        run: |
          kubectl get csr -o=jsonpath='{range.items[?(@.spec.signerName=="kubernetes.io/kubelet-serving")]}{.metadata.name}{" "}{end}' | xargs kubectl certificate approve
      - name: Update Helm dependencies
        run: make dep-update
      - name: Run instrumentation CR e2e tests
        id: run-e2e
        run: make functionaltest SUITE=instrumentation_cr
      - name: Collect Kubernetes Cluster debug info on failure
        if: always() && steps.run-e2e.outcome == 'failure'
        run: |
          echo "Instrumentation CR tests failed. Collecting debug info..."
          cd tools
          ./splunk_kubernetes_debug_info.sh
      - name: Upload Kubernetes Cluster debug info
        if: always() && steps.run-e2e.outcome == 'failure'
        uses: actions/upload-artifact@v6
        with:
          name: k8s-debug-info-instrumentation-cr
          path: tools/splunk_kubernetes_debug_info_*
          retention-days: 5
