name: remote-management-functional-test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  remote-management-functional:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'Ignore Tests') }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - uses: ./.github/actions/functional-test
        with:
          k8s-version: v1.36.1
          suite: remote_management
          go-version-file: functional_tests/go.mod
          build-test-images: 'false'
          artifact-suffix: remote-management
